using Flowzy.Service.Backup;using Flowzy.Service.Contracts;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;
namespace Flowzy.Api.Controllers;
[ApiController,Authorize(Roles="ADMIN"),Route("api/admin/backups")]
public sealed class BackupController(IBackupService service):ControllerBase{private string Email=>User.Identity!.Name!;
[HttpPost]public async Task<ActionResult<ApiResponse<BackupJobResponse>>>Create(CancellationToken ct)=>Ok(ApiResponse<BackupJobResponse>.Success(await service.Create(Email,ct),"Backup job queued successfully"));
[HttpPost("restore"),Consumes("multipart/form-data")]public async Task<ActionResult<ApiResponse<RestoreBackupResponse>>>Restore([FromForm]IFormFile file,[FromForm]string confirmation,CancellationToken ct){if(file is null||file.Length==0)throw new Flowzy.Service.Exceptions.BadRequestException("Backup file is required");await using var s=file.OpenReadStream();return Ok(ApiResponse<RestoreBackupResponse>.Success(await service.Restore(s,file.FileName,confirmation,Email,ct),"Database restored successfully"));}
[HttpGet]public async Task<ActionResult<ApiResponse<PageResponse<BackupJobResponse>>>>List([FromQuery]string? status,[FromQuery]int page=0,[FromQuery]int size=10,CancellationToken ct=default)=>Ok(ApiResponse<PageResponse<BackupJobResponse>>.Success(await service.List(status,page,size,ct),"Backup jobs retrieved successfully"));
[HttpGet("schedule")]public async Task<ActionResult<ApiResponse<BackupScheduleResponse>>>Schedule(CancellationToken ct)=>Ok(ApiResponse<BackupScheduleResponse>.Success(await service.Schedule(ct),"Backup schedule retrieved successfully"));
[HttpPut("schedule")]public async Task<ActionResult<ApiResponse<BackupScheduleResponse>>>Update(UpdateBackupScheduleRequest r,CancellationToken ct)=>Ok(ApiResponse<BackupScheduleResponse>.Success(await service.Update(r,Email,ct),"Backup schedule updated successfully"));
[HttpGet("{jobId:long}")]public async Task<ActionResult<ApiResponse<BackupJobResponse>>>Get(long jobId,CancellationToken ct)=>Ok(ApiResponse<BackupJobResponse>.Success(await service.Get(jobId,ct),"Backup job retrieved successfully"));
[HttpGet("{jobId:long}/download")]public async Task<IActionResult>Download(long jobId,CancellationToken ct){var f=await service.Download(jobId,ct);Response.Headers.ContentDisposition=$"attachment; filename=\"{f.Name}\"";return PhysicalFile(f.Path,"application/octet-stream");}}
