using Flowzy.Service.Contracts;using Flowzy.Service.Dashboard;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;
namespace Flowzy.Api.Controllers;
[ApiController,Authorize,Route("api/dashboard")]
public sealed class DashboardController(IDashboardService service):ControllerBase{private string Email=>User.Identity!.Name!;private async Task<ActionResult<ApiResponse<object>>>R(string v,string? term,string? course,long? gid,string? status,int page,int size,int limit,CancellationToken ct,string message)=>Ok(ApiResponse<object>.Success(await service.Get(v,Email,term,course,gid,status,page,size,limit,ct),message));
[HttpGet("admin/groups"),Authorize(Roles="ADMIN")]public Task<ActionResult<ApiResponse<object>>>AG(CancellationToken ct)=>R("admin/groups",null,null,null,null,0,20,5,ct,"Admin dashboard groups retrieved successfully");[HttpGet("admin/projects"),Authorize(Roles="ADMIN")]public Task<ActionResult<ApiResponse<object>>>AP(CancellationToken ct)=>R("admin/projects",null,null,null,null,0,20,5,ct,"Admin dashboard projects retrieved successfully");[HttpGet("admin/mentors"),Authorize(Roles="ADMIN")]public Task<ActionResult<ApiResponse<object>>>AM(CancellationToken ct)=>R("admin/mentors",null,null,null,null,0,20,5,ct,"Admin dashboard mentors retrieved successfully");[HttpGet("admin/timeline"),Authorize(Roles="ADMIN")]public Task<ActionResult<ApiResponse<object>>>AT(CancellationToken ct)=>R("admin/timeline",null,null,null,null,0,20,5,ct,"Admin dashboard timeline retrieved successfully");[HttpGet("admin/execution-status"),Authorize(Roles="ADMIN")]public Task<ActionResult<ApiResponse<object>>>AE(CancellationToken ct)=>R("admin/execution-status",null,null,null,null,0,20,5,ct,"Admin dashboard execution status retrieved successfully");
[HttpGet("admin/overview"),Authorize(Roles="ADMIN")]public Task<ActionResult<ApiResponse<object>>>AO([FromQuery]string? term,[FromQuery]string? courseCode,[FromQuery]int limit=5,CancellationToken ct=default)=>R("admin/overview",term,courseCode,null,null,0,20,limit,ct,"Admin dashboard overview retrieved successfully");
[HttpGet("tv-showcase/projects"),AllowAnonymous]public Task<ActionResult<ApiResponse<object>>>TP([FromQuery]string? term,[FromQuery]string? courseCode,[FromQuery]int page=0,[FromQuery]int size=20,CancellationToken ct=default)=>R("tv-showcase/projects",term,courseCode,null,null,page,size,5,ct,"TV showcase projects retrieved successfully");[HttpGet("tv-showcase/recruitments"),AllowAnonymous]public Task<ActionResult<ApiResponse<object>>>TR([FromQuery]string? term,[FromQuery]string? courseCode,[FromQuery]int page=0,[FromQuery]int size=20,CancellationToken ct=default)=>R("tv-showcase/recruitments",term,courseCode,null,null,page,size,5,ct,"TV showcase recruitments retrieved successfully");
[HttpGet("mentor/groups"),Authorize(Roles="MENTOR")]public Task<ActionResult<ApiResponse<object>>>MG(CancellationToken ct)=>R("mentor/groups",null,null,null,null,0,20,5,ct,"Mentor dashboard groups retrieved successfully");[HttpGet("mentor/meetings"),Authorize(Roles="MENTOR")]public Task<ActionResult<ApiResponse<object>>>MM([FromQuery]string status="ALL",CancellationToken ct=default)=>R("mentor/meetings",null,null,null,status,0,20,5,ct,"Mentor dashboard meetings retrieved successfully");
[HttpGet("instructor/milestones"),Authorize(Roles="INSTRUCTOR")]public Task<ActionResult<ApiResponse<object>>>IM([FromQuery]string? term,[FromQuery]string? courseCode,[FromQuery]long? groupId,CancellationToken ct)=>R("instructor/milestones",term,courseCode,groupId,null,0,20,5,ct,"Instructor dashboard milestones retrieved successfully");
[HttpGet("student/groups"),Authorize(Roles="STUDENT")]public Task<ActionResult<ApiResponse<object>>>SG(CancellationToken ct)=>R("student/groups",null,null,null,null,0,20,5,ct,"Student dashboard groups retrieved successfully");[HttpGet("student/progress"),Authorize(Roles="STUDENT")]public Task<ActionResult<ApiResponse<object>>>SP(CancellationToken ct)=>R("student/progress",null,null,null,null,0,20,5,ct,"Student dashboard progress retrieved successfully");[HttpGet("student/projects"),Authorize(Roles="STUDENT")]public Task<ActionResult<ApiResponse<object>>>SJ(CancellationToken ct)=>R("student/projects",null,null,null,null,0,20,5,ct,"Student dashboard projects retrieved successfully");[HttpGet("student/milestones"),Authorize(Roles="STUDENT")]public Task<ActionResult<ApiResponse<object>>>SM([FromQuery]long groupId,CancellationToken ct)=>R("student/milestones",null,null,groupId,null,0,20,5,ct,"Student dashboard milestones retrieved successfully");}
