using Flowzy.Service.Contracts;using Flowzy.Service.Mentors;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;
namespace Flowzy.Api.Controllers;
[ApiController,Authorize,Route("api/groups/{groupId:long}/mentor")]
public sealed class GroupMeetingController(IGroupMeetingService service):ControllerBase{private string Email=>User.Identity!.Name!;
[HttpGet("availability")]public async Task<ActionResult<ApiResponse<IReadOnlyList<MentorAvailabilitySlotResponse>>>>Availability(long groupId,CancellationToken ct)=>Ok(ApiResponse<IReadOnlyList<MentorAvailabilitySlotResponse>>.Success(await service.Availability(groupId,Email,ct),"Available slots retrieved successfully"));
[HttpPost("meetings")]public async Task<ActionResult<ApiResponse<MeetingResponse>>>Create(long groupId,CreateOrBookMeetingRequest r,CancellationToken ct)=>Ok(ApiResponse<MeetingResponse>.Success(await service.Create(groupId,r,Email,ct),r.SlotId is null?"Meeting created successfully":"Meeting booked successfully"));
[HttpPatch("meetings/{meetingId:long}")]public async Task<ActionResult<ApiResponse<MeetingResponse>>>Update(long groupId,long meetingId,UpdateMeetingRequest r,CancellationToken ct)=>Ok(ApiResponse<MeetingResponse>.Success(await service.Update(groupId,meetingId,r,Email,ct),"Meeting updated successfully"));
[HttpPut("meetings/{meetingId:long}/evidence")]public async Task<ActionResult<ApiResponse<MeetingResponse>>>Evidence(long groupId,long meetingId,SubmitMeetingEvidenceRequest r,CancellationToken ct)=>Ok(ApiResponse<MeetingResponse>.Success(await service.Evidence(groupId,meetingId,r.ImageUrl,Email,ct),"Meeting evidence submitted successfully"));
[HttpPatch("meetings/{meetingId:long}/cancel")]public async Task<ActionResult<ApiResponse<MeetingResponse>>>Cancel(long groupId,long meetingId,CancelMeetingRequest r,CancellationToken ct)=>Ok(ApiResponse<MeetingResponse>.Success(await service.Cancel(groupId,meetingId,r.Reason,Email,ct),"Meeting canceled successfully"));
[HttpPatch("meetings/{meetingId:long}/confirm")]public async Task<ActionResult<ApiResponse<MeetingResponse>>>Confirm(long groupId,long meetingId,CancellationToken ct)=>Ok(ApiResponse<MeetingResponse>.Success(await service.Confirm(groupId,meetingId,Email,ct),"Meeting confirmation saved successfully"));
[HttpGet("meetings")]public async Task<ActionResult<ApiResponse<IReadOnlyList<MeetingResponse>>>>List(long groupId,CancellationToken ct)=>Ok(ApiResponse<IReadOnlyList<MeetingResponse>>.Success(await service.List(groupId,Email,ct),"Group meetings retrieved successfully"));
[HttpGet("meetings/{meetingId:long}")]public async Task<ActionResult<ApiResponse<MeetingResponse>>>Get(long groupId,long meetingId,CancellationToken ct)=>Ok(ApiResponse<MeetingResponse>.Success(await service.Get(groupId,meetingId,Email,ct),"Group meeting detail retrieved successfully"));}
