using Flowzy.Service.Contracts;
using Flowzy.Service.Groups;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Flowzy.Api.Controllers;
[ApiController,Authorize,Route("api/groups")]
public sealed class GroupController(IGroupOperationsService service, Flowzy.Service.Timelines.ICourseMilestoneService timelines):ControllerBase
{
 private string Email=>User.Identity!.Name!;
 [HttpGet] public async Task<ActionResult<ApiResponse<IReadOnlyList<GroupSummaryResponse>>>> List([FromQuery]string? search,[FromQuery]string? status,[FromQuery]string? neededRole,[FromQuery]string? roleCategory,CancellationToken ct)=>Ok(ApiResponse<IReadOnlyList<GroupSummaryResponse>>.Success(await service.ListAsync(search,status,neededRole,roleCategory,ct),"Groups retrieved successfully"));
 [HttpGet("discover"),Authorize(Roles="STUDENT")] public async Task<ActionResult<ApiResponse<PageResponse<GroupSummaryResponse>>>> Discover([FromQuery]int page=0,[FromQuery]int size=12,[FromQuery]string? name=null,[FromQuery]decimal? studentGpa=null,[FromQuery]string? neededRole=null,CancellationToken ct=default)=>Ok(ApiResponse<PageResponse<GroupSummaryResponse>>.Success(await service.DiscoverAsync(page,size,name,studentGpa,neededRole,Email,ct),"Discover groups retrieved successfully"));
 [HttpGet("{id:long}")] public async Task<ActionResult<ApiResponse<object>>> Get(long id,CancellationToken ct)=>Ok(ApiResponse<object>.Success(await service.DetailAsync(id,ct),"Group details retrieved successfully"));
 [HttpPatch("{id:long}/criteria")] public async Task<ActionResult<ApiResponse<object>>> Criteria(long id,UpdateGroupCriteriaRequest request,CancellationToken ct)=>Ok(ApiResponse<object>.Success(await service.CriteriaAsync(id,request,Email,ct),"Group criteria updated successfully"));
 [HttpGet("mentor/me"),Authorize(Roles="MENTOR")] public async Task<ActionResult<ApiResponse<IReadOnlyList<GroupSummaryResponse>>>> Mentor(CancellationToken ct)=>Ok(ApiResponse<IReadOnlyList<GroupSummaryResponse>>.Success(await service.MineAsync("mentor",Email,null,null,ct),"Assigned groups retrieved successfully"));
 [HttpGet("student/me"),Authorize(Roles="STUDENT")] public async Task<ActionResult<ApiResponse<IReadOnlyList<GroupSummaryResponse>>>> Student(CancellationToken ct)=>Ok(ApiResponse<IReadOnlyList<GroupSummaryResponse>>.Success(await service.MineAsync("student",Email,null,null,ct),"Student group retrieved successfully"));
 [HttpGet("instructor/me"),Authorize(Roles="INSTRUCTOR")] public async Task<ActionResult<ApiResponse<IReadOnlyList<GroupSummaryResponse>>>> Instructor([FromQuery]string? term,[FromQuery]string? courseCode,CancellationToken ct)=>Ok(ApiResponse<IReadOnlyList<GroupSummaryResponse>>.Success(await service.MineAsync("instructor",Email,term,courseCode,ct),"Assigned groups retrieved successfully"));
 [HttpPost,Authorize(Roles="STUDENT")] public async Task<ActionResult<ApiResponse<object>>> Create(CreateGroupRequest request,CancellationToken ct)=>Ok(ApiResponse<object>.Success(await service.CreateAsync(request,Email,ct),"Group created successfully"));
 [HttpPatch("{id:long}")] public async Task<ActionResult<ApiResponse<object>>> Update(long id,UpdateGroupRequest request,CancellationToken ct)=>Ok(ApiResponse<object>.Success(await service.UpdateAsync(id,request,Email,ct),"Group updated successfully"));
 [HttpDelete("{groupId:long}/members/{studentId:long}")] public async Task<ActionResult<ApiResponse<object>>> Remove(long groupId,long studentId,CancellationToken ct){await service.RemoveAsync(groupId,studentId,Email,ct);return Ok(ApiResponse<object>.Success(null,"Member removed successfully"));}
 [HttpDelete("{groupId:long}/members/me"),HttpPost("{groupId:long}/leave"),Authorize(Roles="STUDENT")] public async Task<ActionResult<ApiResponse<object>>> Leave(long groupId,CancellationToken ct){await service.LeaveAsync(groupId,Email,ct);return Ok(ApiResponse<object>.Success(null,"Left group successfully"));}
 [HttpPatch("{groupId:long}/leader")] public async Task<ActionResult<ApiResponse<object>>> Transfer(long groupId,TransferLeaderRequest request,CancellationToken ct){await service.TransferAsync(groupId,request.StudentId,Email,ct);return Ok(ApiResponse<object>.Success(null,"Leadership transferred successfully"));}
 [HttpPatch("{groupId:long}/instructor"),Authorize(Roles="ADMIN")] public async Task<ActionResult<ApiResponse<object>>> AssignInstructor(long groupId,AssignInstructorRequest r,CancellationToken ct)=>Ok(ApiResponse<object>.Success(await service.AssignAsync(groupId,"instructor",r.InstructorId,ct),"Instructor assigned to group successfully"));
 [HttpDelete("{groupId:long}/instructor"),Authorize(Roles="ADMIN")] public async Task<ActionResult<ApiResponse<object>>> UnassignInstructor(long groupId,CancellationToken ct)=>Ok(ApiResponse<object>.Success(await service.AssignAsync(groupId,"instructor",null,ct),"Instructor unassigned from group successfully"));
 [HttpPatch("{groupId:long}/mentor"),Authorize(Roles="ADMIN")] public async Task<ActionResult<ApiResponse<object>>> AssignMentor(long groupId,AssignMentorRequest r,CancellationToken ct)=>Ok(ApiResponse<object>.Success(await service.AssignAsync(groupId,"mentor",r.MentorId,ct),"Mentor assigned to group successfully"));
 [HttpDelete("{groupId:long}/mentor"),Authorize(Roles="ADMIN")] public async Task<ActionResult<ApiResponse<object>>> UnassignMentor(long groupId,CancellationToken ct)=>Ok(ApiResponse<object>.Success(await service.AssignAsync(groupId,"mentor",null,ct),"Mentor unassigned from group successfully"));
 [HttpGet("{groupId:long}/milestones")] public async Task<ActionResult<ApiResponse<IReadOnlyList<CourseMilestoneResponse>>>> Milestones(long groupId,CancellationToken ct)=>Ok(ApiResponse<IReadOnlyList<CourseMilestoneResponse>>.Success(await timelines.GroupMilestonesAsync(groupId,Email,ct),"Group timeline retrieved successfully"));
 [HttpPatch("{groupId:long}/lock"),Authorize(Roles="STUDENT")] public async Task<ActionResult<ApiResponse<object>>> Lock(long groupId,UpdateGroupLockRequest r,CancellationToken ct)=>Ok(ApiResponse<object>.Success(await service.LockAsync(groupId,r.IsLock,Email,ct),r.IsLock?"Group locked successfully":"Group unlocked successfully"));
}
