using Flowzy.Service.Contracts;using Flowzy.Service.Grades;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;
namespace Flowzy.Api.Controllers;
[ApiController,Authorize]
public sealed class MilestoneGradeMatrixController(IGradeMatrixService service):ControllerBase{private string Email=>User.Identity!.Name!;
[HttpPut("api/instructor/milestones/{milestoneId:long}/groups/{groupId:long}/grade"),Authorize(Roles="INSTRUCTOR")]public async Task<ActionResult<ApiResponse<object>>>Grade(long milestoneId,long groupId,UpsertGroupGradeRequest r,CancellationToken ct)=>Ok(ApiResponse<object>.Success(await service.Grade(milestoneId,groupId,r,Email,ct),"Group milestone grade saved successfully"));
[HttpPut("api/groups/{groupId:long}/milestones/{milestoneId:long}/contributions")]public async Task<ActionResult<ApiResponse<object>>>Contributions(long groupId,long milestoneId,UpsertContributionsRequest r,CancellationToken ct)=>Ok(ApiResponse<object>.Success(await service.Contributions(groupId,milestoneId,r,Email,ct),"Milestone contributions saved successfully"));
[HttpPut("api/groups/{groupId:long}/milestones/{milestoneId:long}/contribution-agreement")]public async Task<ActionResult<ApiResponse<object>>>Agreement(long groupId,long milestoneId,ContributionAgreementRequest r,CancellationToken ct)=>Ok(ApiResponse<object>.Success(await service.Agreement(groupId,milestoneId,r,Email,ct),"Contribution response saved successfully"));
[HttpGet("api/groups/{groupId:long}/grades")]public async Task<ActionResult<ApiResponse<object>>>Matrix(long groupId,CancellationToken ct)=>Ok(ApiResponse<object>.Success(await service.Matrix(groupId,Email,ct),"Group grade matrix retrieved successfully"));
[HttpGet("api/instructor/grades/export.csv"),Authorize(Roles="INSTRUCTOR")]public async Task<IActionResult>Csv([FromQuery]string? term,[FromQuery]string? courseCode,[FromQuery]long? groupId,CancellationToken ct){var b=await service.Export(term,courseCode,groupId,Email,false,ct);Response.Headers.ContentDisposition = "attachment; filename=\"" + Name("csv",term,courseCode) + "\""; return File([0xEF,0xBB,0xBF,..b],"text/csv; charset=utf-8");}
[HttpGet("api/instructor/grades/export.xlsx"),Authorize(Roles="INSTRUCTOR")]public async Task<IActionResult>Xlsx([FromQuery]string? term,[FromQuery]string? courseCode,[FromQuery]long? groupId,CancellationToken ct){var bytes=await service.Export(term,courseCode,groupId,Email,true,ct); Response.Headers.ContentDisposition = "attachment; filename=\"" + Name("xlsx",term,courseCode) + "\""; return File(bytes,"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");}
private static string Name(string ext,string? term,string? course)=>$"grades-{(string.IsNullOrWhiteSpace(term)?"all-terms":term.Trim())}-{(string.IsNullOrWhiteSpace(course)?"all-courses":course.Trim())}.{ext}";}
