-- Migration: V11__create_group_task_board.sql
-- Description: Create tables, constraints, indexes, and triggers for Phase 8 Group Task Board.

-- 1. Create group_tasks table
CREATE TABLE IF NOT EXISTS group_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    status VARCHAR(30) NOT NULL DEFAULT 'BACKLOG',
    priority VARCHAR(30) NOT NULL DEFAULT 'MEDIUM',
    due_at TIMESTAMPTZ,
    position BIGINT NOT NULL,
    created_by_student_id BIGINT NOT NULL,
    archived_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_group_tasks_group FOREIGN KEY (group_id) REFERENCES student_groups(id) ON DELETE CASCADE,
    CONSTRAINT fk_group_tasks_created_by FOREIGN KEY (created_by_student_id) REFERENCES students(id),
    CONSTRAINT chk_group_tasks_status CHECK (status IN ('BACKLOG', 'TODO', 'IN_PROGRESS', 'REVIEW', 'DONE')),
    CONSTRAINT chk_group_tasks_priority CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'URGENT'))
);

CREATE INDEX IF NOT EXISTS idx_group_tasks_board_load ON group_tasks(group_id, archived_at, status, position);
CREATE INDEX IF NOT EXISTS idx_group_tasks_due_status ON group_tasks(due_at, status);
CREATE INDEX IF NOT EXISTS idx_group_tasks_priority ON group_tasks(priority);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgname = 'update_group_tasks_updated_at'
          AND tgrelid = 'group_tasks'::regclass
    ) THEN
        CREATE TRIGGER update_group_tasks_updated_at
            BEFORE UPDATE ON group_tasks
            FOR EACH ROW
            EXECUTE FUNCTION update_updated_at_column();
    END IF;
END;
$$;

-- 2. Create task_assignees table
CREATE TABLE IF NOT EXISTS task_assignees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    assigned_by_student_id BIGINT NOT NULL,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_task_assignees_task FOREIGN KEY (task_id) REFERENCES group_tasks(id) ON DELETE CASCADE,
    CONSTRAINT fk_task_assignees_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
    CONSTRAINT fk_task_assignees_assigned_by FOREIGN KEY (assigned_by_student_id) REFERENCES students(id),
    CONSTRAINT uq_task_assignees_task_student UNIQUE (task_id, student_id)
);

CREATE INDEX IF NOT EXISTS idx_task_assignees_student_task ON task_assignees(student_id, task_id);

-- 3. Create task_checklist_items table
CREATE TABLE IF NOT EXISTS task_checklist_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    title VARCHAR(500) NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    completed_by_account_id BIGINT,
    completed_at TIMESTAMPTZ,
    position BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_task_checklist_items_task FOREIGN KEY (task_id) REFERENCES group_tasks(id) ON DELETE CASCADE,
    CONSTRAINT fk_task_checklist_items_completed_by FOREIGN KEY (completed_by_account_id) REFERENCES accounts(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_task_checklist_items_task_pos ON task_checklist_items(task_id, position);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgname = 'update_task_checklist_items_updated_at'
          AND tgrelid = 'task_checklist_items'::regclass
    ) THEN
        CREATE TRIGGER update_task_checklist_items_updated_at
            BEFORE UPDATE ON task_checklist_items
            FOR EACH ROW
            EXECUTE FUNCTION update_updated_at_column();
    END IF;
END;
$$;

-- 4. Create task_comments table
CREATE TABLE IF NOT EXISTS task_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    author_account_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    edited_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_task_comments_task FOREIGN KEY (task_id) REFERENCES group_tasks(id) ON DELETE CASCADE,
    CONSTRAINT fk_task_comments_author FOREIGN KEY (author_account_id) REFERENCES accounts(id)
);

CREATE INDEX IF NOT EXISTS idx_task_comments_task_created ON task_comments(task_id, created_at DESC);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgname = 'update_task_comments_updated_at'
          AND tgrelid = 'task_comments'::regclass
    ) THEN
        CREATE TRIGGER update_task_comments_updated_at
            BEFORE UPDATE ON task_comments
            FOR EACH ROW
            EXECUTE FUNCTION update_updated_at_column();
    END IF;
END;
$$;

-- 5. Create task_activities table
CREATE TABLE IF NOT EXISTS task_activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    group_id BIGINT NOT NULL,
    actor_account_id BIGINT,
    activity_type VARCHAR(50) NOT NULL,
    details JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_task_activities_task FOREIGN KEY (task_id) REFERENCES group_tasks(id) ON DELETE CASCADE,
    CONSTRAINT fk_task_activities_group FOREIGN KEY (group_id) REFERENCES student_groups(id) ON DELETE CASCADE,
    CONSTRAINT fk_task_activities_actor FOREIGN KEY (actor_account_id) REFERENCES accounts(id) ON DELETE SET NULL,
    CONSTRAINT chk_task_activities_type CHECK (activity_type IN (
        'TASK_CREATED',
        'TASK_UPDATED',
        'TASK_MOVED',
        'ASSIGNEES_CHANGED',
        'CHECKLIST_ITEM_CREATED',
        'CHECKLIST_ITEM_UPDATED',
        'CHECKLIST_ITEM_DELETED',
        'COMMENT_CREATED',
        'COMMENT_UPDATED',
        'COMMENT_DELETED',
        'TASK_ARCHIVED',
        'TASK_RESTORED',
        'ASSIGNEE_REMOVED_FROM_GROUP'
    ))
);

CREATE INDEX IF NOT EXISTS idx_task_activities_task_created ON task_activities(task_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_task_activities_group_created ON task_activities(group_id, created_at DESC);
