-- Migration: V12__create_group_join_requests_and_kanban_boards.sql
-- Description: Create task_boards and group_join_requests tables, backfill task_boards, and associate group_tasks.

-- 1. Create task_boards table
CREATE TABLE IF NOT EXISTS task_boards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    position BIGINT NOT NULL DEFAULT 0,
    default_board BOOLEAN NOT NULL DEFAULT FALSE,
    created_by_student_id BIGINT,
    archived_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_task_boards_group FOREIGN KEY (group_id) REFERENCES student_groups(id) ON DELETE CASCADE,
    CONSTRAINT fk_task_boards_created_by FOREIGN KEY (created_by_student_id) REFERENCES students(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_task_boards_group_id ON task_boards(group_id);
CREATE INDEX IF NOT EXISTS idx_task_boards_created_by ON task_boards(created_by_student_id);

-- Register update trigger for task_boards
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgname = 'update_task_boards_updated_at'
          AND tgrelid = 'task_boards'::regclass
    ) THEN
        CREATE TRIGGER update_task_boards_updated_at
            BEFORE UPDATE ON task_boards
            FOR EACH ROW
            EXECUTE FUNCTION update_updated_at_column();
    END IF;
END;
$$;

-- 2. Create group_join_requests table
CREATE TABLE IF NOT EXISTS group_join_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    message VARCHAR(500),
    responded_by_student_id BIGINT,
    responded_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_group_join_requests_group FOREIGN KEY (group_id) REFERENCES student_groups(id) ON DELETE CASCADE,
    CONSTRAINT fk_group_join_requests_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
    CONSTRAINT fk_group_join_requests_responded_by FOREIGN KEY (responded_by_student_id) REFERENCES students(id) ON DELETE SET NULL,
    CONSTRAINT chk_group_join_requests_status CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELED'))
);

CREATE INDEX IF NOT EXISTS idx_group_join_requests_group_id ON group_join_requests(group_id);
CREATE INDEX IF NOT EXISTS idx_group_join_requests_student_id ON group_join_requests(student_id);
CREATE INDEX IF NOT EXISTS idx_group_join_requests_status ON group_join_requests(status);
CREATE INDEX IF NOT EXISTS idx_group_join_requests_responded_by ON group_join_requests(responded_by_student_id);

-- Unique index to prevent multiple concurrent PENDING join requests by the same student to the same group
CREATE UNIQUE INDEX IF NOT EXISTS uq_group_join_requests_pending
ON group_join_requests(group_id, student_id)
WHERE status = 'PENDING';

-- Register update trigger for group_join_requests
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgname = 'update_group_join_requests_updated_at'
          AND tgrelid = 'group_join_requests'::regclass
    ) THEN
        CREATE TRIGGER update_group_join_requests_updated_at
            BEFORE UPDATE ON group_join_requests
            FOR EACH ROW
            EXECUTE FUNCTION update_updated_at_column();
    END IF;
END;
$$;

-- 3. Backfill default task boards for all existing student groups (set name to course_code, default_board = true)
INSERT INTO task_boards (group_id, name, description, position, default_board, created_at, updated_at)
SELECT id, course_code, 'Default Board', 0, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM student_groups;

-- 4. Add board_id to group_tasks
ALTER TABLE group_tasks ADD COLUMN IF NOT EXISTS board_id BIGINT;

-- Backfill board_id mapping group_tasks to the newly created default task_board for their group
UPDATE group_tasks gt
SET board_id = tb.id
FROM task_boards tb
WHERE gt.group_id = tb.group_id AND gt.board_id IS NULL;

-- Enforce NOT NULL constraint on board_id
ALTER TABLE group_tasks ALTER COLUMN board_id SET NOT NULL;

-- Add foreign key constraint to board_id
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_group_tasks_board'
          AND conrelid = 'group_tasks'::regclass
    ) THEN
        ALTER TABLE group_tasks
            ADD CONSTRAINT fk_group_tasks_board
            FOREIGN KEY (board_id) REFERENCES task_boards(id) ON DELETE CASCADE;
    END IF;
END;
$$;

-- Drop old index and recreate with board_id
DROP INDEX IF EXISTS idx_group_tasks_board_load;
CREATE INDEX IF NOT EXISTS idx_group_tasks_board_load ON group_tasks(board_id, archived_at, status, position);

-- Create index on board_id
CREATE INDEX IF NOT EXISTS idx_group_tasks_board_id ON group_tasks(board_id);
