-- Migration: V13__add_instructor_and_milestones.sql
-- Description: Implement tables and schema modifications for Phase 10 - Milestone I1

-- 1. Alter accounts table constraint to include 'INSTRUCTOR'
ALTER TABLE accounts DROP CONSTRAINT IF EXISTS chk_accounts_role;
ALTER TABLE accounts ADD CONSTRAINT chk_accounts_role CHECK (role IN ('ADMIN', 'STUDENT', 'MENTOR', 'INSTRUCTOR'));

-- 2. Create instructors table
CREATE TABLE IF NOT EXISTS instructors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL UNIQUE,
    instructor_code VARCHAR(50) NOT NULL UNIQUE,
    full_name VARCHAR(255) NOT NULL,
    phone VARCHAR(30),
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_instructors_account FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE,
    CONSTRAINT chk_instructors_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'LOCKED'))
);

CREATE INDEX IF NOT EXISTS idx_instructors_full_name ON instructors(full_name);

-- Register update trigger for instructors
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgname = 'update_instructors_updated_at'
          AND tgrelid = 'instructors'::regclass
    ) THEN
        CREATE TRIGGER update_instructors_updated_at
            BEFORE UPDATE ON instructors
            FOR EACH ROW
            EXECUTE FUNCTION update_updated_at_column();
    END IF;
END;
$$;

-- 3. Add instructor_id column to student_groups table
ALTER TABLE student_groups ADD COLUMN IF NOT EXISTS instructor_id BIGINT;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_student_groups_instructor'
          AND conrelid = 'student_groups'::regclass
    ) THEN
        ALTER TABLE student_groups
            ADD CONSTRAINT fk_student_groups_instructor
            FOREIGN KEY (instructor_id) REFERENCES instructors(id) ON DELETE SET NULL;
    END IF;
END;
$$;

CREATE INDEX IF NOT EXISTS idx_student_groups_instructor_id ON student_groups(instructor_id);

-- 4. Create course_milestones table
CREATE TABLE IF NOT EXISTS course_milestones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instructor_id BIGINT,
    term VARCHAR(30) NOT NULL,
    course_code VARCHAR(30) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    weight INTEGER NOT NULL,
    due_date TIMESTAMPTZ,
    type VARCHAR(30) NOT NULL DEFAULT 'CHECKPOINT',
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_course_milestones_instructor FOREIGN KEY (instructor_id) REFERENCES instructors(id) ON DELETE SET NULL,
    CONSTRAINT chk_course_milestones_type CHECK (type IN ('CHECKPOINT', 'OUTCOME')),
    CONSTRAINT chk_course_milestones_status CHECK (status IN ('ACTIVE', 'ARCHIVED')),
    CONSTRAINT chk_course_milestones_weight CHECK (weight >= 0),
    CONSTRAINT uq_course_milestones_term_course_title UNIQUE (term, course_code, title)
);

CREATE INDEX IF NOT EXISTS idx_course_milestones_instructor_id ON course_milestones(instructor_id);
CREATE INDEX IF NOT EXISTS idx_course_milestones_term_course ON course_milestones(term, course_code);

-- Register update trigger for course_milestones
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgname = 'update_course_milestones_updated_at'
          AND tgrelid = 'course_milestones'::regclass
    ) THEN
        CREATE TRIGGER update_course_milestones_updated_at
            BEFORE UPDATE ON course_milestones
            FOR EACH ROW
            EXECUTE FUNCTION update_updated_at_column();
    END IF;
END;
$$;

-- 5. Create milestone_outcomes table
CREATE TABLE IF NOT EXISTS milestone_outcomes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    milestone_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    required_type VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_milestone_outcomes_milestone FOREIGN KEY (milestone_id) REFERENCES course_milestones(id) ON DELETE CASCADE,
    CONSTRAINT chk_milestone_outcomes_type CHECK (required_type IN ('LINK', 'FILE', 'TEXT'))
);

CREATE INDEX IF NOT EXISTS idx_milestone_outcomes_milestone_id ON milestone_outcomes(milestone_id);

-- Register update trigger for milestone_outcomes
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgname = 'update_milestone_outcomes_updated_at'
          AND tgrelid = 'milestone_outcomes'::regclass
    ) THEN
        CREATE TRIGGER update_milestone_outcomes_updated_at
            BEFORE UPDATE ON milestone_outcomes
            FOR EACH ROW
            EXECUTE FUNCTION update_updated_at_column();
    END IF;
END;
$$;

-- 6. Create milestone_submissions table
CREATE TABLE IF NOT EXISTS milestone_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    milestone_id BIGINT NOT NULL,
    group_id BIGINT NOT NULL,
    submitted_by VARCHAR(255),
    file_url VARCHAR(1000),
    comments TEXT,
    submitted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    late BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(30) NOT NULL DEFAULT 'SUBMITTED',
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_milestone_submissions_milestone FOREIGN KEY (milestone_id) REFERENCES course_milestones(id) ON DELETE CASCADE,
    CONSTRAINT fk_milestone_submissions_group FOREIGN KEY (group_id) REFERENCES student_groups(id) ON DELETE CASCADE,
    CONSTRAINT uq_milestone_submissions_milestone_group UNIQUE (milestone_id, group_id),
    CONSTRAINT chk_milestone_submissions_status CHECK (status IN ('SUBMITTED', 'GRADED'))
);

CREATE INDEX IF NOT EXISTS idx_milestone_submissions_milestone_id ON milestone_submissions(milestone_id);
CREATE INDEX IF NOT EXISTS idx_milestone_submissions_group_id ON milestone_submissions(group_id);

-- Register update trigger for milestone_submissions
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgname = 'update_milestone_submissions_updated_at'
          AND tgrelid = 'milestone_submissions'::regclass
    ) THEN
        CREATE TRIGGER update_milestone_submissions_updated_at
            BEFORE UPDATE ON milestone_submissions
            FOR EACH ROW
            EXECUTE FUNCTION update_updated_at_column();
    END IF;
END;
$$;

-- 7. Create milestone_grades table
CREATE TABLE IF NOT EXISTS milestone_grades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id BIGINT NOT NULL UNIQUE,
    instructor_id BIGINT,
    score DECIMAL(5,2) NOT NULL,
    feedback TEXT,
    graded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_milestone_grades_submission FOREIGN KEY (submission_id) REFERENCES milestone_submissions(id) ON DELETE CASCADE,
    CONSTRAINT fk_milestone_grades_instructor FOREIGN KEY (instructor_id) REFERENCES instructors(id) ON DELETE SET NULL,
    CONSTRAINT chk_milestone_grades_score CHECK (score >= 0.00)
);

CREATE INDEX IF NOT EXISTS idx_milestone_grades_submission_id ON milestone_grades(submission_id);
CREATE INDEX IF NOT EXISTS idx_milestone_grades_instructor_id ON milestone_grades(instructor_id);

-- Register update trigger for milestone_grades
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgname = 'update_milestone_grades_updated_at'
          AND tgrelid = 'milestone_grades'::regclass
    ) THEN
        CREATE TRIGGER update_milestone_grades_updated_at
            BEFORE UPDATE ON milestone_grades
            FOR EACH ROW
            EXECUTE FUNCTION update_updated_at_column();
    END IF;
END;
$$;
