-- Migration: V19__add_academic_terms_and_feedback.sql
-- Description: Add academic terms and feedback snapshot tables, backfill existing terms, and enforce constraints.

-- 1. Create academic_terms table
CREATE TABLE IF NOT EXISTS academic_terms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(30) NOT NULL UNIQUE,
    status VARCHAR(30) NOT NULL DEFAULT 'OPEN',
    closed_at TIMESTAMPTZ,
    closed_by_account_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_academic_terms_closed_by FOREIGN KEY (closed_by_account_id) REFERENCES accounts(id) ON DELETE SET NULL,
    CONSTRAINT chk_academic_terms_status CHECK (status IN ('OPEN', 'CLOSED'))
);

CREATE INDEX IF NOT EXISTS idx_academic_terms_closed_by ON academic_terms(closed_by_account_id);

-- Register update trigger for academic_terms
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgname = 'update_academic_terms_updated_at'
          AND tgrelid = 'academic_terms'::regclass
    ) THEN
        CREATE TRIGGER update_academic_terms_updated_at
            BEFORE UPDATE ON academic_terms
            FOR EACH ROW
            EXECUTE FUNCTION update_updated_at_column();
    END IF;
END;
$$;

-- 2. Backfill existing terms
-- We first normalize existing values in student_groups to ensure consistency
UPDATE student_groups SET term = TRIM(UPPER(term));

-- Then we insert the distinct normalized terms as 'OPEN' into academic_terms
INSERT INTO academic_terms (code, status, created_at, updated_at)
SELECT DISTINCT term, 'OPEN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM student_groups
WHERE term IS NOT NULL AND TRIM(term) <> ''
ON CONFLICT (code) DO NOTHING;

-- 3. Add foreign key from student_groups(term) to academic_terms(code)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_student_groups_academic_term'
          AND conrelid = 'student_groups'::regclass
    ) THEN
        ALTER TABLE student_groups
            ADD CONSTRAINT fk_student_groups_academic_term
            FOREIGN KEY (term) REFERENCES academic_terms(code);
    END IF;
END;
$$;

-- 4. Create term_feedbacks table
CREATE TABLE IF NOT EXISTS term_feedbacks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    academic_term_id BIGINT NOT NULL,
    group_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    target_type VARCHAR(30) NOT NULL,
    mentor_id BIGINT,
    instructor_id BIGINT,
    rating INTEGER,
    comment TEXT,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    submitted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_term_feedbacks_academic_term FOREIGN KEY (academic_term_id) REFERENCES academic_terms(id) ON DELETE CASCADE,
    CONSTRAINT fk_term_feedbacks_group FOREIGN KEY (group_id) REFERENCES student_groups(id) ON DELETE CASCADE,
    CONSTRAINT fk_term_feedbacks_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
    CONSTRAINT fk_term_feedbacks_mentor FOREIGN KEY (mentor_id) REFERENCES mentors(id) ON DELETE CASCADE,
    CONSTRAINT fk_term_feedbacks_instructor FOREIGN KEY (instructor_id) REFERENCES instructors(id) ON DELETE CASCADE,
    CONSTRAINT uq_term_feedbacks_term_group_student_target UNIQUE (academic_term_id, group_id, student_id, target_type),
    CONSTRAINT chk_term_feedbacks_status CHECK (status IN ('PENDING', 'SUBMITTED')),
    CONSTRAINT chk_term_feedbacks_target_type CHECK (target_type IN ('MENTOR', 'INSTRUCTOR')),
    CONSTRAINT chk_term_feedbacks_rating CHECK (rating IS NULL OR (rating >= 1 AND rating <= 5)),
    CONSTRAINT chk_term_feedbacks_target_exclusivity CHECK (
        (target_type = 'MENTOR' AND mentor_id IS NOT NULL AND instructor_id IS NULL) OR
        (target_type = 'INSTRUCTOR' AND instructor_id IS NOT NULL AND mentor_id IS NULL)
    )
);

-- Triggers for term_feedbacks
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgname = 'update_term_feedbacks_updated_at'
          AND tgrelid = 'term_feedbacks'::regclass
    ) THEN
        CREATE TRIGGER update_term_feedbacks_updated_at
            BEFORE UPDATE ON term_feedbacks
            FOR EACH ROW
            EXECUTE FUNCTION update_updated_at_column();
    END IF;
END;
$$;

-- Indexes for term_feedbacks
CREATE INDEX IF NOT EXISTS idx_term_feedbacks_student_status ON term_feedbacks (student_id, status);
CREATE INDEX IF NOT EXISTS idx_term_feedbacks_mentor_term_status ON term_feedbacks (mentor_id, academic_term_id, status);
CREATE INDEX IF NOT EXISTS idx_term_feedbacks_instructor_term_status ON term_feedbacks (instructor_id, academic_term_id, status);
CREATE INDEX IF NOT EXISTS idx_term_feedbacks_group_id ON term_feedbacks (group_id);
CREATE INDEX IF NOT EXISTS idx_term_feedbacks_target_type ON term_feedbacks (target_type);
