CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TABLE accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    must_change_password BOOLEAN NOT NULL DEFAULT TRUE,
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_accounts_role CHECK (role IN ('ADMIN', 'STUDENT', 'MENTOR')),
    CONSTRAINT chk_accounts_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'LOCKED'))
);

CREATE INDEX idx_accounts_role_status ON accounts(role, status);

CREATE TRIGGER update_accounts_updated_at
    BEFORE UPDATE ON accounts
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_refresh_tokens_account FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE,
    CONSTRAINT chk_refresh_tokens_dates CHECK (expires_at > created_at)
);

CREATE INDEX idx_refresh_tokens_account_id ON refresh_tokens(account_id);

CREATE TABLE students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL UNIQUE,
    student_code VARCHAR(50) NOT NULL UNIQUE,
    full_name VARCHAR(255) NOT NULL,
    phone VARCHAR(30),
    date_of_birth DATE,
    gender VARCHAR(20),
    address TEXT,
    major VARCHAR(150),
    cohort VARCHAR(50),
    class_name VARCHAR(100),
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_students_account FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE,
    CONSTRAINT chk_students_gender CHECK (gender IN ('MALE', 'FEMALE', 'OTHER')),
    CONSTRAINT chk_students_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE INDEX idx_students_full_name ON students(full_name);
CREATE INDEX idx_students_cohort_class ON students(cohort, class_name);

CREATE TRIGGER update_students_updated_at
    BEFORE UPDATE ON students
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TABLE mentors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL UNIQUE,
    mentor_code VARCHAR(50) NOT NULL UNIQUE,
    full_name VARCHAR(255) NOT NULL,
    phone VARCHAR(30),
    job_title VARCHAR(150),
    company VARCHAR(150),
    expertise TEXT,
    years_of_experience INTEGER,
    linkedin_url VARCHAR(500),
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_mentors_account FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE,
    CONSTRAINT chk_mentors_experience CHECK (years_of_experience >= 0),
    CONSTRAINT chk_mentors_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE INDEX idx_mentors_full_name ON mentors(full_name);
CREATE INDEX idx_mentors_company ON mentors(company);

CREATE TRIGGER update_mentors_updated_at
    BEFORE UPDATE ON mentors
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TABLE import_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type VARCHAR(30) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_type VARCHAR(20) NOT NULL,
    status VARCHAR(30) NOT NULL,
    total_rows INTEGER NOT NULL,
    success_rows INTEGER NOT NULL,
    failed_rows INTEGER NOT NULL,
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at TIMESTAMPTZ,
    created_by BIGINT,
    CONSTRAINT fk_import_batches_creator FOREIGN KEY (created_by) REFERENCES accounts(id) ON DELETE SET NULL,
    CONSTRAINT chk_import_batches_target CHECK (target_type IN ('STUDENT', 'MENTOR')),
    CONSTRAINT chk_import_batches_file_type CHECK (file_type IN ('CSV', 'XLSX')),
    CONSTRAINT chk_import_batches_status CHECK (status IN ('COMPLETED', 'FAILED')),
    CONSTRAINT chk_import_batches_total_rows CHECK (total_rows >= 0),
    CONSTRAINT chk_import_batches_success_rows CHECK (success_rows >= 0),
    CONSTRAINT chk_import_batches_failed_rows CHECK (failed_rows >= 0),
    CONSTRAINT chk_import_batches_counts CHECK (success_rows + failed_rows <= total_rows),
    CONSTRAINT chk_import_batches_dates CHECK (finished_at IS NULL OR finished_at >= started_at)
);

CREATE INDEX idx_import_batches_created_by ON import_batches(created_by);
CREATE INDEX idx_import_batches_started_at ON import_batches(started_at DESC);

CREATE TABLE import_row_errors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL,
    row_number INTEGER NOT NULL,
    field_name VARCHAR(100),
    error_code VARCHAR(80) NOT NULL,
    error_message TEXT NOT NULL,
    raw_data JSONB,
    CONSTRAINT fk_import_row_errors_batch FOREIGN KEY (batch_id) REFERENCES import_batches(id) ON DELETE CASCADE,
    CONSTRAINT chk_import_row_errors_row CHECK (row_number > 0)
);

CREATE INDEX idx_import_row_errors_batch_id ON import_row_errors(batch_id);
CREATE INDEX idx_import_row_errors_batch_row ON import_row_errors(batch_id, row_number);
