-- Migration: V20__add_group_recruitment_needs.sql
-- Description: Create group_recruitment_needs table and indexes.

-- Create group_recruitment_needs table
CREATE TABLE IF NOT EXISTS group_recruitment_needs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    role VARCHAR(100) NOT NULL,
    quantity INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_group_recruitment_needs_group FOREIGN KEY (group_id) REFERENCES student_groups(id) ON DELETE CASCADE,
    CONSTRAINT uq_group_recruitment_needs_group_role UNIQUE (group_id, role),
    CONSTRAINT chk_group_recruitment_needs_quantity CHECK (quantity >= 1 AND quantity <= 6)
);

-- Register update trigger for group_recruitment_needs
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgname = 'update_group_recruitment_needs_updated_at'
          AND tgrelid = 'group_recruitment_needs'::regclass
    ) THEN
        CREATE TRIGGER update_group_recruitment_needs_updated_at
            BEFORE UPDATE ON group_recruitment_needs
            FOR EACH ROW
            EXECUTE FUNCTION update_updated_at_column();
    END IF;
END;
$$;

-- Index for group discovery
CREATE INDEX IF NOT EXISTS idx_group_recruitment_needs_role_group ON group_recruitment_needs (role, group_id);
