-- Migration: V23__instructor_review_meeting_confirmations_and_flexible_grades.sql
-- Description: Instructor problem review, mentor meeting confirmations, and submission-independent milestone grades.

ALTER TABLE mentor_meetings DROP CONSTRAINT IF EXISTS chk_mentor_meetings_status;
ALTER TABLE mentor_meetings ADD CONSTRAINT chk_mentor_meetings_status CHECK (status IN ('SCHEDULED', 'CANCELED', 'COMPLETED'));

ALTER TABLE mentor_meetings ADD COLUMN IF NOT EXISTS leader_confirmed_by_student_id BIGINT;
ALTER TABLE mentor_meetings ADD COLUMN IF NOT EXISTS leader_confirmed_at TIMESTAMPTZ;
ALTER TABLE mentor_meetings ADD COLUMN IF NOT EXISTS mentor_confirmed_at TIMESTAMPTZ;
ALTER TABLE mentor_meetings ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ;

ALTER TABLE mentor_meetings
    ADD CONSTRAINT fk_mentor_meetings_leader_confirmed_by_student
    FOREIGN KEY (leader_confirmed_by_student_id) REFERENCES students(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS milestone_group_grades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    milestone_id BIGINT NOT NULL,
    group_id BIGINT NOT NULL,
    instructor_id BIGINT,
    score DECIMAL(7,2) NOT NULL,
    max_score_snapshot DECIMAL(7,2) NOT NULL,
    weight_snapshot INTEGER NOT NULL,
    feedback TEXT,
    graded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_milestone_group_grades_milestone FOREIGN KEY (milestone_id) REFERENCES course_milestones(id) ON DELETE CASCADE,
    CONSTRAINT fk_milestone_group_grades_group FOREIGN KEY (group_id) REFERENCES student_groups(id) ON DELETE CASCADE,
    CONSTRAINT fk_milestone_group_grades_instructor FOREIGN KEY (instructor_id) REFERENCES instructors(id) ON DELETE SET NULL,
    CONSTRAINT uq_milestone_group_grades_milestone_group UNIQUE (milestone_id, group_id),
    CONSTRAINT chk_milestone_group_grades_score CHECK (score >= 0.00),
    CONSTRAINT chk_milestone_group_grades_max_score CHECK (max_score_snapshot > 0.00),
    CONSTRAINT chk_milestone_group_grades_weight CHECK (weight_snapshot >= 0 AND weight_snapshot <= 100)
);

CREATE INDEX IF NOT EXISTS idx_milestone_group_grades_milestone_id ON milestone_group_grades(milestone_id);
CREATE INDEX IF NOT EXISTS idx_milestone_group_grades_group_id ON milestone_group_grades(group_id);
CREATE INDEX IF NOT EXISTS idx_milestone_group_grades_instructor_id ON milestone_group_grades(instructor_id);

CREATE TABLE IF NOT EXISTS milestone_member_scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_grade_id BIGINT NOT NULL,
    milestone_id BIGINT NOT NULL,
    group_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    contribution_percent DECIMAL(5,2) NOT NULL,
    calculated_score DECIMAL(7,4) NOT NULL,
    max_score_snapshot DECIMAL(7,2) NOT NULL,
    weight_snapshot INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_milestone_member_scores_group_grade FOREIGN KEY (group_grade_id) REFERENCES milestone_group_grades(id) ON DELETE CASCADE,
    CONSTRAINT fk_milestone_member_scores_milestone FOREIGN KEY (milestone_id) REFERENCES course_milestones(id) ON DELETE CASCADE,
    CONSTRAINT fk_milestone_member_scores_group FOREIGN KEY (group_id) REFERENCES student_groups(id) ON DELETE CASCADE,
    CONSTRAINT fk_milestone_member_scores_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
    CONSTRAINT uq_milestone_member_scores_milestone_group_student UNIQUE (milestone_id, group_id, student_id),
    CONSTRAINT chk_milestone_member_scores_contribution CHECK (contribution_percent >= 0.00 AND contribution_percent <= 100.00),
    CONSTRAINT chk_milestone_member_scores_calculated CHECK (calculated_score >= 0.0000),
    CONSTRAINT chk_milestone_member_scores_max_score CHECK (max_score_snapshot > 0.00),
    CONSTRAINT chk_milestone_member_scores_weight CHECK (weight_snapshot >= 0 AND weight_snapshot <= 100)
);

CREATE INDEX IF NOT EXISTS idx_milestone_member_scores_group_grade_id ON milestone_member_scores(group_grade_id);
CREATE INDEX IF NOT EXISTS idx_milestone_member_scores_milestone_id ON milestone_member_scores(milestone_id);
CREATE INDEX IF NOT EXISTS idx_milestone_member_scores_group_id ON milestone_member_scores(group_id);
CREATE INDEX IF NOT EXISTS idx_milestone_member_scores_student_id ON milestone_member_scores(student_id);
