-- Notification v2: client-neutral actions and producer idempotency keys.
-- Legacy action_url/payload remain during the compatibility window.

ALTER TABLE notifications
    ADD COLUMN IF NOT EXISTS action_key VARCHAR(100),
    ADD COLUMN IF NOT EXISTS action_params TEXT,
    ADD COLUMN IF NOT EXISTS event_key VARCHAR(255);

UPDATE notifications
SET action_params = payload
WHERE action_params IS NULL AND payload IS NOT NULL;

UPDATE notifications
SET action_key = CASE type
    WHEN 'GROUP_INVITATION_CREATED' THEN 'OPEN_GROUP_INVITATIONS'
    WHEN 'GROUP_INVITATION_ACCEPTED' THEN 'OPEN_GROUP'
    WHEN 'GROUP_INVITATION_DECLINED' THEN 'OPEN_GROUP'
    WHEN 'GROUP_JOIN_REQUEST_CREATED' THEN 'OPEN_GROUP'
    WHEN 'GROUP_JOIN_REQUEST_APPROVED' THEN 'OPEN_GROUP'
    WHEN 'GROUP_JOIN_REQUEST_REJECTED' THEN 'OPEN_GROUP'
    WHEN 'GROUP_MEMBER_REMOVED' THEN 'OPEN_GROUP'
    WHEN 'GROUP_LEADER_TRANSFERRED' THEN 'OPEN_GROUP'
    WHEN 'GROUP_LOCK_UPDATED' THEN 'OPEN_GROUP'
    WHEN 'TASK_ASSIGNED' THEN 'OPEN_TASK'
    WHEN 'TASK_COMMENT_CREATED' THEN 'OPEN_TASK'
    WHEN 'TASK_STATUS_CHANGED' THEN 'OPEN_TASK'
    WHEN 'TIMELINE_ITEM_CREATED' THEN 'OPEN_MILESTONE'
    WHEN 'TIMELINE_ITEM_UPDATED' THEN 'OPEN_MILESTONE'
    WHEN 'MILESTONE_SUBMISSION_CREATED' THEN 'OPEN_SUBMISSION'
    WHEN 'MILESTONE_SUBMISSION_GRADED' THEN 'OPEN_GRADES'
    WHEN 'MILESTONE_GROUP_GRADED' THEN 'OPEN_GRADES'
    WHEN 'MENTOR_MEETING_BOOKED' THEN 'OPEN_MEETING'
    WHEN 'MENTOR_MEETING_CANCELED' THEN 'OPEN_MEETING'
    WHEN 'MENTOR_MEETING_CONFIRMED' THEN 'OPEN_MEETING'
    WHEN 'MENTOR_MEETING_COMPLETED' THEN 'OPEN_MEETING'
    WHEN 'TERM_FEEDBACK_AVAILABLE' THEN 'OPEN_FEEDBACK'
    ELSE 'NONE'
END
WHERE action_key IS NULL;

CREATE INDEX IF NOT EXISTS idx_notifications_recipient_created_id
    ON notifications (recipient_id, created_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_notifications_unread_created_id
    ON notifications (recipient_id, created_at DESC, id DESC)
    WHERE read_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_notifications_recipient_event_key
    ON notifications (recipient_id, event_key)
    WHERE event_key IS NOT NULL;
