CREATE TABLE IF NOT EXISTS backup_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trigger_type VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    file_name VARCHAR(255),
    file_path VARCHAR(1000),
    file_size_bytes BIGINT,
    error_message TEXT,
    requested_by_account_id BIGINT,
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_backup_jobs_requested_by FOREIGN KEY (requested_by_account_id) REFERENCES accounts(id) ON DELETE SET NULL,
    CONSTRAINT chk_backup_jobs_trigger_type CHECK (trigger_type IN ('MANUAL', 'SCHEDULED')),
    CONSTRAINT chk_backup_jobs_status CHECK (status IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED'))
);

CREATE INDEX IF NOT EXISTS idx_backup_jobs_created_at_id ON backup_jobs(created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_backup_jobs_status ON backup_jobs(status);
CREATE INDEX IF NOT EXISTS idx_backup_jobs_requested_by ON backup_jobs(requested_by_account_id);

CREATE TABLE IF NOT EXISTS backup_schedule_settings (
    id BIGINT PRIMARY KEY,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    cron_expression VARCHAR(120) NOT NULL DEFAULT '0 0 2 * * *',
    timezone VARCHAR(120) NOT NULL DEFAULT 'Asia/Ho_Chi_Minh',
    backup_dir VARCHAR(1000) NOT NULL DEFAULT '/var/backups/fspark/postgres',
    retention_days INTEGER NOT NULL DEFAULT 14,
    last_triggered_at TIMESTAMPTZ,
    next_run_at TIMESTAMPTZ,
    updated_by_account_id BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_backup_schedule_settings_updated_by FOREIGN KEY (updated_by_account_id) REFERENCES accounts(id) ON DELETE SET NULL,
    CONSTRAINT chk_backup_schedule_settings_retention CHECK (retention_days BETWEEN 1 AND 3650)
);

INSERT INTO backup_schedule_settings (
    id,
    enabled,
    cron_expression,
    timezone,
    backup_dir,
    retention_days,
    updated_at
) VALUES (
    1,
    FALSE,
    '0 0 2 * * *',
    'Asia/Ho_Chi_Minh',
    '/var/backups/fspark/postgres',
    14,
    CURRENT_TIMESTAMP
) ON CONFLICT (id) DO NOTHING;
