-- Guard for local databases that were baselined at V1 before V1 created tables.
-- On healthy databases these statements are no-ops.
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TABLE IF NOT EXISTS accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    must_change_password BOOLEAN NOT NULL DEFAULT TRUE,
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_accounts_role CHECK (role IN ('ADMIN', 'STUDENT', 'MENTOR')),
    CONSTRAINT chk_accounts_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'LOCKED'))
);

CREATE INDEX IF NOT EXISTS idx_accounts_role_status ON accounts(role, status);

CREATE TABLE IF NOT EXISTS refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_refresh_tokens_account FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE,
    CONSTRAINT chk_refresh_tokens_dates CHECK (expires_at > created_at)
);

CREATE INDEX IF NOT EXISTS idx_refresh_tokens_account_id ON refresh_tokens(account_id);

CREATE TABLE IF NOT EXISTS students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL UNIQUE,
    student_code VARCHAR(50) NOT NULL UNIQUE,
    full_name VARCHAR(255) NOT NULL,
    phone VARCHAR(30),
    date_of_birth DATE,
    gender VARCHAR(20),
    address TEXT,
    major VARCHAR(150),
    cohort VARCHAR(50),
    class_name VARCHAR(100),
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_students_account FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE,
    CONSTRAINT chk_students_gender CHECK (gender IN ('MALE', 'FEMALE', 'OTHER')),
    CONSTRAINT chk_students_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE INDEX IF NOT EXISTS idx_students_full_name ON students(full_name);
CREATE INDEX IF NOT EXISTS idx_students_cohort_class ON students(cohort, class_name);

CREATE TABLE IF NOT EXISTS mentors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL UNIQUE,
    mentor_code VARCHAR(50) NOT NULL UNIQUE,
    full_name VARCHAR(255) NOT NULL,
    phone VARCHAR(30),
    job_title VARCHAR(150),
    company VARCHAR(150),
    expertise TEXT,
    years_of_experience INTEGER,
    linkedin_url VARCHAR(500),
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_mentors_account FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE,
    CONSTRAINT chk_mentors_experience CHECK (years_of_experience >= 0),
    CONSTRAINT chk_mentors_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE INDEX IF NOT EXISTS idx_mentors_full_name ON mentors(full_name);
CREATE INDEX IF NOT EXISTS idx_mentors_company ON mentors(company);

CREATE TABLE IF NOT EXISTS import_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type VARCHAR(30) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_type VARCHAR(20) NOT NULL,
    status VARCHAR(30) NOT NULL,
    total_rows INTEGER NOT NULL,
    success_rows INTEGER NOT NULL,
    failed_rows INTEGER NOT NULL,
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at TIMESTAMPTZ,
    created_by BIGINT,
    CONSTRAINT fk_import_batches_creator FOREIGN KEY (created_by) REFERENCES accounts(id) ON DELETE SET NULL,
    CONSTRAINT chk_import_batches_target CHECK (target_type IN ('STUDENT', 'MENTOR')),
    CONSTRAINT chk_import_batches_file_type CHECK (file_type IN ('CSV', 'XLSX')),
    CONSTRAINT chk_import_batches_status CHECK (status IN ('COMPLETED', 'FAILED')),
    CONSTRAINT chk_import_batches_total_rows CHECK (total_rows >= 0),
    CONSTRAINT chk_import_batches_success_rows CHECK (success_rows >= 0),
    CONSTRAINT chk_import_batches_failed_rows CHECK (failed_rows >= 0),
    CONSTRAINT chk_import_batches_counts CHECK (success_rows + failed_rows <= total_rows),
    CONSTRAINT chk_import_batches_dates CHECK (finished_at IS NULL OR finished_at >= started_at)
);

CREATE INDEX IF NOT EXISTS idx_import_batches_created_by ON import_batches(created_by);
CREATE INDEX IF NOT EXISTS idx_import_batches_started_at ON import_batches(started_at DESC);

CREATE TABLE IF NOT EXISTS import_row_errors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL,
    row_number INTEGER NOT NULL,
    field_name VARCHAR(100),
    error_code VARCHAR(80) NOT NULL,
    error_message TEXT NOT NULL,
    raw_data JSONB,
    CONSTRAINT fk_import_row_errors_batch FOREIGN KEY (batch_id) REFERENCES import_batches(id) ON DELETE CASCADE,
    CONSTRAINT chk_import_row_errors_row CHECK (row_number > 0)
);

CREATE INDEX IF NOT EXISTS idx_import_row_errors_batch_id ON import_row_errors(batch_id);
CREATE INDEX IF NOT EXISTS idx_import_row_errors_batch_row ON import_row_errors(batch_id, row_number);

-- Create student_groups table.
-- The IF NOT EXISTS and guarded ALTER blocks keep local dev databases that were
-- previously updated by Hibernate from failing before Flyway can own this schema.
CREATE TABLE IF NOT EXISTS student_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    term VARCHAR(30) NOT NULL,
    course_code VARCHAR(30) NOT NULL,
    group_no VARCHAR(30) NOT NULL,
    name VARCHAR(255) NOT NULL,
    project_name VARCHAR(255),
    idea_description TEXT,
    research_domain TEXT,
    leader_student_id BIGINT,
    required_gpa DECIMAL(3,2),
    target_grade DECIMAL(3,1),
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    import_batch_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_student_groups_leader FOREIGN KEY (leader_student_id) REFERENCES students(id) ON DELETE SET NULL,
    CONSTRAINT fk_student_groups_import_batch FOREIGN KEY (import_batch_id) REFERENCES import_batches(id) ON DELETE SET NULL,
    CONSTRAINT chk_student_groups_status CHECK (status IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT chk_student_groups_required_gpa CHECK (required_gpa >= 0.00 AND required_gpa <= 4.00),
    CONSTRAINT chk_student_groups_target_grade CHECK (target_grade >= 0.0 AND target_grade <= 10.0),
    CONSTRAINT uq_student_groups_term_course_group_no UNIQUE (term, course_code, group_no)
);

ALTER TABLE student_groups ADD COLUMN IF NOT EXISTS term VARCHAR(30);
ALTER TABLE student_groups ADD COLUMN IF NOT EXISTS course_code VARCHAR(30);
ALTER TABLE student_groups ADD COLUMN IF NOT EXISTS group_no VARCHAR(30);
ALTER TABLE student_groups ADD COLUMN IF NOT EXISTS name VARCHAR(255);
ALTER TABLE student_groups ADD COLUMN IF NOT EXISTS project_name VARCHAR(255);
ALTER TABLE student_groups ADD COLUMN IF NOT EXISTS idea_description TEXT;
ALTER TABLE student_groups ADD COLUMN IF NOT EXISTS research_domain TEXT;
ALTER TABLE student_groups ADD COLUMN IF NOT EXISTS leader_student_id BIGINT;
ALTER TABLE student_groups ADD COLUMN IF NOT EXISTS required_gpa DECIMAL(3,2);
ALTER TABLE student_groups ADD COLUMN IF NOT EXISTS target_grade DECIMAL(3,1);
ALTER TABLE student_groups ADD COLUMN IF NOT EXISTS status VARCHAR(30) DEFAULT 'ACTIVE';
ALTER TABLE student_groups ADD COLUMN IF NOT EXISTS import_batch_id BIGINT;
ALTER TABLE student_groups ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE student_groups ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;

UPDATE student_groups
SET term = 'LEGACY'
WHERE term IS NULL;

UPDATE student_groups
SET course_code = 'LEGACY'
WHERE course_code IS NULL;

UPDATE student_groups
SET group_no = CONCAT('LEGACY-', id)
WHERE group_no IS NULL;

UPDATE student_groups
SET name = CONCAT('Legacy Group ', id)
WHERE name IS NULL;

UPDATE student_groups
SET status = 'ACTIVE'
WHERE status IS NULL OR status NOT IN ('ACTIVE', 'INACTIVE');

UPDATE student_groups
SET leader_student_id = NULL
WHERE leader_student_id IS NOT NULL
  AND NOT EXISTS (
      SELECT 1 FROM students s
      WHERE s.id = student_groups.leader_student_id
  );

UPDATE student_groups
SET import_batch_id = NULL
WHERE import_batch_id IS NOT NULL
  AND NOT EXISTS (
      SELECT 1 FROM import_batches ib
      WHERE ib.id = student_groups.import_batch_id
  );

UPDATE student_groups
SET required_gpa = NULL
WHERE required_gpa IS NOT NULL
  AND (required_gpa < 0.00 OR required_gpa > 4.00);

UPDATE student_groups
SET target_grade = NULL
WHERE target_grade IS NOT NULL
  AND (target_grade < 0.0 OR target_grade > 10.0);

UPDATE student_groups
SET created_at = CURRENT_TIMESTAMP
WHERE created_at IS NULL;

UPDATE student_groups
SET updated_at = CURRENT_TIMESTAMP
WHERE updated_at IS NULL;

ALTER TABLE student_groups ALTER COLUMN term SET NOT NULL;
ALTER TABLE student_groups ALTER COLUMN course_code SET NOT NULL;
ALTER TABLE student_groups ALTER COLUMN group_no SET NOT NULL;
ALTER TABLE student_groups ALTER COLUMN name SET NOT NULL;
ALTER TABLE student_groups ALTER COLUMN status SET DEFAULT 'ACTIVE';
ALTER TABLE student_groups ALTER COLUMN status SET NOT NULL;
ALTER TABLE student_groups ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE student_groups ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE student_groups ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE student_groups ALTER COLUMN updated_at SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_student_groups_leader'
          AND conrelid = 'student_groups'::regclass
    ) THEN
        ALTER TABLE student_groups
            ADD CONSTRAINT fk_student_groups_leader
            FOREIGN KEY (leader_student_id) REFERENCES students(id) ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_student_groups_import_batch'
          AND conrelid = 'student_groups'::regclass
    ) THEN
        ALTER TABLE student_groups
            ADD CONSTRAINT fk_student_groups_import_batch
            FOREIGN KEY (import_batch_id) REFERENCES import_batches(id) ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'chk_student_groups_status'
          AND conrelid = 'student_groups'::regclass
    ) THEN
        ALTER TABLE student_groups
            ADD CONSTRAINT chk_student_groups_status
            CHECK (status IN ('ACTIVE', 'INACTIVE'));
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'chk_student_groups_required_gpa'
          AND conrelid = 'student_groups'::regclass
    ) THEN
        ALTER TABLE student_groups
            ADD CONSTRAINT chk_student_groups_required_gpa
            CHECK (required_gpa >= 0.00 AND required_gpa <= 4.00);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'chk_student_groups_target_grade'
          AND conrelid = 'student_groups'::regclass
    ) THEN
        ALTER TABLE student_groups
            ADD CONSTRAINT chk_student_groups_target_grade
            CHECK (target_grade >= 0.0 AND target_grade <= 10.0);
    END IF;

    WITH duplicated_groups AS (
        SELECT id,
               ROW_NUMBER() OVER (
                   PARTITION BY term, course_code, group_no
                   ORDER BY id
               ) AS duplicate_rank
        FROM student_groups
    )
    UPDATE student_groups sg
    SET group_no = CONCAT('DUP-', sg.id)
    FROM duplicated_groups dg
    WHERE sg.id = dg.id
      AND dg.duplicate_rank > 1;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'uq_student_groups_term_course_group_no'
          AND conrelid = 'student_groups'::regclass
    ) THEN
        ALTER TABLE student_groups
            ADD CONSTRAINT uq_student_groups_term_course_group_no
            UNIQUE (term, course_code, group_no);
    END IF;
END;
$$;

CREATE INDEX IF NOT EXISTS idx_student_groups_term_course ON student_groups(term, course_code);
CREATE INDEX IF NOT EXISTS idx_student_groups_import_batch ON student_groups(import_batch_id);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgname = 'update_student_groups_updated_at'
          AND tgrelid = 'student_groups'::regclass
    ) THEN
        CREATE TRIGGER update_student_groups_updated_at
            BEFORE UPDATE ON student_groups
            FOR EACH ROW
            EXECUTE FUNCTION update_updated_at_column();
    END IF;
END;
$$;

-- Create student_group_members table
CREATE TABLE IF NOT EXISTS student_group_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    member_role VARCHAR(30) NOT NULL DEFAULT 'MEMBER',
    joined_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_student_group_members_group FOREIGN KEY (group_id) REFERENCES student_groups(id) ON DELETE CASCADE,
    CONSTRAINT fk_student_group_members_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
    CONSTRAINT chk_student_group_members_role CHECK (member_role IN ('LEADER', 'MEMBER')),
    CONSTRAINT uq_student_group_members_group_student UNIQUE (group_id, student_id)
);

ALTER TABLE student_group_members ADD COLUMN IF NOT EXISTS group_id BIGINT;
ALTER TABLE student_group_members ADD COLUMN IF NOT EXISTS student_id BIGINT;
ALTER TABLE student_group_members ADD COLUMN IF NOT EXISTS member_role VARCHAR(30) DEFAULT 'MEMBER';
ALTER TABLE student_group_members ADD COLUMN IF NOT EXISTS joined_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;

DELETE FROM student_group_members
WHERE group_id IS NULL OR student_id IS NULL;

DELETE FROM student_group_members sgm
WHERE NOT EXISTS (
    SELECT 1 FROM student_groups sg
    WHERE sg.id = sgm.group_id
)
OR NOT EXISTS (
    SELECT 1 FROM students s
    WHERE s.id = sgm.student_id
);

UPDATE student_group_members
SET member_role = 'MEMBER'
WHERE member_role IS NULL OR member_role NOT IN ('LEADER', 'MEMBER');

UPDATE student_group_members
SET joined_at = CURRENT_TIMESTAMP
WHERE joined_at IS NULL;

DELETE FROM student_group_members sgm
USING student_group_members duplicate
WHERE sgm.group_id = duplicate.group_id
  AND sgm.student_id = duplicate.student_id
  AND sgm.id > duplicate.id;

ALTER TABLE student_group_members ALTER COLUMN group_id SET NOT NULL;
ALTER TABLE student_group_members ALTER COLUMN student_id SET NOT NULL;
ALTER TABLE student_group_members ALTER COLUMN member_role SET DEFAULT 'MEMBER';
ALTER TABLE student_group_members ALTER COLUMN member_role SET NOT NULL;
ALTER TABLE student_group_members ALTER COLUMN joined_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE student_group_members ALTER COLUMN joined_at SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_student_group_members_group'
          AND conrelid = 'student_group_members'::regclass
    ) THEN
        ALTER TABLE student_group_members
            ADD CONSTRAINT fk_student_group_members_group
            FOREIGN KEY (group_id) REFERENCES student_groups(id) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_student_group_members_student'
          AND conrelid = 'student_group_members'::regclass
    ) THEN
        ALTER TABLE student_group_members
            ADD CONSTRAINT fk_student_group_members_student
            FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'chk_student_group_members_role'
          AND conrelid = 'student_group_members'::regclass
    ) THEN
        ALTER TABLE student_group_members
            ADD CONSTRAINT chk_student_group_members_role
            CHECK (member_role IN ('LEADER', 'MEMBER'));
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'uq_student_group_members_group_student'
          AND conrelid = 'student_group_members'::regclass
    ) THEN
        ALTER TABLE student_group_members
            ADD CONSTRAINT uq_student_group_members_group_student
            UNIQUE (group_id, student_id);
    END IF;
END;
$$;

CREATE INDEX IF NOT EXISTS idx_student_group_members_group_id ON student_group_members(group_id);
CREATE INDEX IF NOT EXISTS idx_student_group_members_student_id ON student_group_members(student_id);

-- Enforce membership constraint: A student can belong to only one group per term + course_code
CREATE OR REPLACE FUNCTION check_student_group_membership_limit()
RETURNS TRIGGER AS $$
DECLARE
    v_term VARCHAR(30);
    v_course_code VARCHAR(30);
BEGIN
    SELECT term, course_code INTO v_term, v_course_code
    FROM student_groups
    WHERE id = NEW.group_id;

    IF EXISTS (
        SELECT 1 
        FROM student_group_members sgm
        JOIN student_groups sg ON sgm.group_id = sg.id
        WHERE sgm.student_id = NEW.student_id
          AND sg.term = v_term
          AND sg.course_code = v_course_code
          AND sgm.id <> COALESCE(NEW.id, -1)
    ) THEN
        RAISE EXCEPTION 'Student is already a member of a group in the same term and course';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgname = 'trigger_check_student_group_membership'
          AND tgrelid = 'student_group_members'::regclass
    ) THEN
        CREATE TRIGGER trigger_check_student_group_membership
            BEFORE INSERT OR UPDATE ON student_group_members
            FOR EACH ROW
            EXECUTE FUNCTION check_student_group_membership_limit();
    END IF;
END;
$$;

-- Trigger to prevent term/course updates from breaking membership uniqueness
CREATE OR REPLACE FUNCTION check_group_term_course_update()
RETURNS TRIGGER AS $$
BEGIN
    IF (OLD.term <> NEW.term OR OLD.course_code <> NEW.course_code) THEN
        IF EXISTS (
            SELECT 1 FROM student_group_members sgm1
            JOIN student_group_members sgm2 ON sgm1.student_id = sgm2.student_id
            WHERE sgm1.group_id = NEW.id
              AND sgm2.group_id <> NEW.id
              AND sgm2.group_id IN (
                  SELECT id FROM student_groups 
                  WHERE term = NEW.term AND course_code = NEW.course_code
              )
        ) THEN
            RAISE EXCEPTION 'Cannot update group term/course because it would violate student membership uniqueness constraint';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgname = 'trigger_check_group_term_course_update'
          AND tgrelid = 'student_groups'::regclass
    ) THEN
        CREATE TRIGGER trigger_check_group_term_course_update
            BEFORE UPDATE ON student_groups
            FOR EACH ROW
            EXECUTE FUNCTION check_group_term_course_update();
    END IF;
END;
$$;
