-- Mentor-managed meeting reports and unanimous contribution agreements.

ALTER TABLE mentor_meetings ADD COLUMN IF NOT EXISTS start_at TIMESTAMPTZ;
ALTER TABLE mentor_meetings ADD COLUMN IF NOT EXISTS end_at TIMESTAMPTZ;
ALTER TABLE mentor_meetings ADD COLUMN IF NOT EXISTS note VARCHAR(500);
ALTER TABLE mentor_meetings ADD COLUMN IF NOT EXISTS evidence_image_url VARCHAR(2000);
ALTER TABLE mentor_meetings ADD COLUMN IF NOT EXISTS evidence_submitted_by_student_id BIGINT;
ALTER TABLE mentor_meetings ADD COLUMN IF NOT EXISTS evidence_submitted_at TIMESTAMPTZ;

UPDATE mentor_meetings m
SET start_at = s.start_at,
    end_at = s.end_at
FROM mentor_availability_slots s
WHERE m.slot_id = s.id
  AND (m.start_at IS NULL OR m.end_at IS NULL);

ALTER TABLE mentor_meetings ALTER COLUMN start_at SET NOT NULL;
ALTER TABLE mentor_meetings ALTER COLUMN end_at SET NOT NULL;
ALTER TABLE mentor_meetings ALTER COLUMN slot_id DROP NOT NULL;
ALTER TABLE mentor_meetings ALTER COLUMN booked_by_student_id DROP NOT NULL;
ALTER TABLE mentor_meetings ALTER COLUMN meet_link DROP NOT NULL;

ALTER TABLE mentor_meetings
    ADD CONSTRAINT fk_mentor_meetings_evidence_submitted_by
    FOREIGN KEY (evidence_submitted_by_student_id) REFERENCES students(id) ON DELETE SET NULL;
ALTER TABLE mentor_meetings
    ADD CONSTRAINT chk_mentor_meetings_direct_dates CHECK (end_at > start_at);

CREATE INDEX IF NOT EXISTS idx_mentor_meetings_mentor_start_end
    ON mentor_meetings(mentor_id, start_at, end_at);

CREATE TABLE milestone_contribution_revisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    milestone_id BIGINT NOT NULL,
    group_id BIGINT NOT NULL,
    revision INTEGER NOT NULL DEFAULT 1,
    submitted_by_student_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_contribution_revisions_milestone FOREIGN KEY (milestone_id) REFERENCES course_milestones(id) ON DELETE CASCADE,
    CONSTRAINT fk_contribution_revisions_group FOREIGN KEY (group_id) REFERENCES student_groups(id) ON DELETE CASCADE,
    CONSTRAINT fk_contribution_revisions_submitter FOREIGN KEY (submitted_by_student_id) REFERENCES students(id) ON DELETE CASCADE,
    CONSTRAINT uq_contribution_revisions_scope UNIQUE (milestone_id, group_id),
    CONSTRAINT chk_contribution_revisions_revision CHECK (revision > 0)
);

CREATE TABLE milestone_contribution_agreements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revision_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    decision VARCHAR(30) NOT NULL,
    reason VARCHAR(1000),
    responded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_contribution_agreements_revision FOREIGN KEY (revision_id) REFERENCES milestone_contribution_revisions(id) ON DELETE CASCADE,
    CONSTRAINT fk_contribution_agreements_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
    CONSTRAINT uq_contribution_agreements_revision_student UNIQUE (revision_id, student_id),
    CONSTRAINT chk_contribution_agreements_decision CHECK (decision IN ('AGREE', 'REQUEST_CHANGES')),
    CONSTRAINT chk_contribution_agreements_reason CHECK (decision <> 'REQUEST_CHANGES' OR reason IS NOT NULL)
);

CREATE INDEX idx_contribution_agreements_revision_id ON milestone_contribution_agreements(revision_id);
CREATE INDEX idx_contribution_agreements_student_id ON milestone_contribution_agreements(student_id);

-- Existing ungraded contribution sets require a fresh unanimous review.
INSERT INTO milestone_contribution_revisions (milestone_id, group_id, revision, submitted_by_student_id)
SELECT DISTINCT scores.milestone_id, scores.group_id, 1, groups.leader_student_id
FROM milestone_member_scores scores
JOIN student_groups groups ON groups.id = scores.group_id
LEFT JOIN milestone_group_grades grades
    ON grades.milestone_id = scores.milestone_id AND grades.group_id = scores.group_id
WHERE grades.id IS NULL AND groups.leader_student_id IS NOT NULL
ON CONFLICT (milestone_id, group_id) DO NOTHING;

CREATE TRIGGER update_milestone_contribution_revisions_updated_at
    BEFORE UPDATE ON milestone_contribution_revisions
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_milestone_contribution_agreements_updated_at
    BEFORE UPDATE ON milestone_contribution_agreements
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
