CREATE TABLE IF NOT EXISTS group_invitations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    inviter_student_id BIGINT NOT NULL,
    invitee_student_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    message VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    responded_at TIMESTAMPTZ,
    
    CONSTRAINT fk_group_invitations_group FOREIGN KEY (group_id) REFERENCES student_groups(id) ON DELETE CASCADE,
    CONSTRAINT fk_group_invitations_inviter FOREIGN KEY (inviter_student_id) REFERENCES students(id) ON DELETE CASCADE,
    CONSTRAINT fk_group_invitations_invitee FOREIGN KEY (invitee_student_id) REFERENCES students(id) ON DELETE CASCADE,
    CONSTRAINT chk_group_invitations_status CHECK (status IN ('PENDING', 'ACCEPTED', 'DECLINED', 'CANCELED'))
);

-- Foreign key indexes
CREATE INDEX IF NOT EXISTS idx_group_invitations_group_id ON group_invitations(group_id);
CREATE INDEX IF NOT EXISTS idx_group_invitations_inviter_student_id ON group_invitations(inviter_student_id);
CREATE INDEX IF NOT EXISTS idx_group_invitations_invitee_student_id ON group_invitations(invitee_student_id);
CREATE INDEX IF NOT EXISTS idx_group_invitations_status ON group_invitations(status);

-- Unique constraint for pending invitations per group + invitee
CREATE UNIQUE INDEX IF NOT EXISTS uq_group_invitations_pending 
ON group_invitations(group_id, invitee_student_id) 
WHERE status = 'PENDING';
