-- Migration: V5__create_mentor_availability_and_meetings.sql

-- 1. Create mentor_availability_slots table
CREATE TABLE IF NOT EXISTS mentor_availability_slots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mentor_id BIGINT NOT NULL,
    start_at TIMESTAMPTZ NOT NULL,
    end_at TIMESTAMPTZ NOT NULL,
    meet_link VARCHAR(500) NOT NULL,
    note VARCHAR(500),
    status VARCHAR(30) NOT NULL DEFAULT 'AVAILABLE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_mentor_availability_slots_mentor FOREIGN KEY (mentor_id) REFERENCES mentors(id) ON DELETE CASCADE,
    CONSTRAINT chk_mentor_availability_slots_status CHECK (status IN ('AVAILABLE', 'BOOKED', 'CANCELED')),
    CONSTRAINT chk_mentor_availability_slots_dates CHECK (end_at > start_at)
);

-- Indexes for mentor_availability_slots
CREATE INDEX IF NOT EXISTS idx_mentor_availability_slots_mentor_id ON mentor_availability_slots(mentor_id);
CREATE INDEX IF NOT EXISTS idx_mentor_availability_slots_start_end ON mentor_availability_slots(start_at, end_at);
CREATE INDEX IF NOT EXISTS idx_mentor_availability_slots_status ON mentor_availability_slots(status);

-- Trigger for mentor_availability_slots updated_at
CREATE TRIGGER update_mentor_availability_slots_updated_at
    BEFORE UPDATE ON mentor_availability_slots
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- 2. Create mentor_meetings table
CREATE TABLE IF NOT EXISTS mentor_meetings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slot_id BIGINT NOT NULL UNIQUE,
    group_id BIGINT NOT NULL,
    mentor_id BIGINT NOT NULL,
    booked_by_student_id BIGINT NOT NULL,
    meet_link VARCHAR(500) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'SCHEDULED',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    canceled_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_mentor_meetings_slot FOREIGN KEY (slot_id) REFERENCES mentor_availability_slots(id) ON DELETE CASCADE,
    CONSTRAINT fk_mentor_meetings_group FOREIGN KEY (group_id) REFERENCES student_groups(id) ON DELETE CASCADE,
    CONSTRAINT fk_mentor_meetings_mentor FOREIGN KEY (mentor_id) REFERENCES mentors(id) ON DELETE CASCADE,
    CONSTRAINT fk_mentor_meetings_booked_by FOREIGN KEY (booked_by_student_id) REFERENCES students(id) ON DELETE CASCADE,
    CONSTRAINT chk_mentor_meetings_status CHECK (status IN ('SCHEDULED', 'CANCELED'))
);

-- Indexes for mentor_meetings
CREATE INDEX IF NOT EXISTS idx_mentor_meetings_group_id ON mentor_meetings(group_id);
CREATE INDEX IF NOT EXISTS idx_mentor_meetings_mentor_id ON mentor_meetings(mentor_id);
CREATE INDEX IF NOT EXISTS idx_mentor_meetings_booked_by_student_id ON mentor_meetings(booked_by_student_id);
CREATE INDEX IF NOT EXISTS idx_mentor_meetings_status ON mentor_meetings(status);

-- Trigger for mentor_meetings updated_at
CREATE TRIGGER update_mentor_meetings_updated_at
    BEFORE UPDATE ON mentor_meetings
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
