-- Migration: V6__create_problem_bank.sql

-- 1. Create problem_domains table
CREATE TABLE IF NOT EXISTS problem_domains (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_problem_domains_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE INDEX IF NOT EXISTS idx_problem_domains_code ON problem_domains(code);
CREATE INDEX IF NOT EXISTS idx_problem_domains_status ON problem_domains(status);

CREATE TRIGGER update_problem_domains_updated_at
    BEFORE UPDATE ON problem_domains
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- 2. Create problems table
CREATE TABLE IF NOT EXISTS problems (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    statement TEXT NOT NULL,
    code VARCHAR(100) UNIQUE,
    strategic_theme VARCHAR(255),
    research_area VARCHAR(255),
    difficulty_level VARCHAR(30) NOT NULL,
    expected_output TEXT,
    source_type VARCHAR(30) NOT NULL DEFAULT 'OFFICIAL',
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    proposed_by_group_id BIGINT,
    proposed_by_student_id BIGINT,
    review_comment TEXT,
    reviewed_by_account_id BIGINT,
    reviewed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_problems_domain FOREIGN KEY (domain_id) REFERENCES problem_domains(id) ON DELETE RESTRICT,
    CONSTRAINT fk_problems_proposed_by_group FOREIGN KEY (proposed_by_group_id) REFERENCES student_groups(id) ON DELETE CASCADE,
    CONSTRAINT fk_problems_proposed_by_student FOREIGN KEY (proposed_by_student_id) REFERENCES students(id) ON DELETE SET NULL,
    CONSTRAINT fk_problems_reviewed_by_account FOREIGN KEY (reviewed_by_account_id) REFERENCES accounts(id) ON DELETE SET NULL,
    CONSTRAINT chk_problems_difficulty CHECK (difficulty_level IN ('BEGINNER', 'INTERMEDIATE', 'ADVANCED')),
    CONSTRAINT chk_problems_source CHECK (source_type IN ('OFFICIAL', 'SELF_PROPOSED')),
    CONSTRAINT chk_problems_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'PENDING_REVIEW', 'APPROVED', 'REJECTED', 'ARCHIVED'))
);

CREATE INDEX IF NOT EXISTS idx_problems_domain_id ON problems(domain_id);
CREATE INDEX IF NOT EXISTS idx_problems_proposed_by_group_id ON problems(proposed_by_group_id);
CREATE INDEX IF NOT EXISTS idx_problems_proposed_by_student_id ON problems(proposed_by_student_id);
CREATE INDEX IF NOT EXISTS idx_problems_reviewed_by_account_id ON problems(reviewed_by_account_id);
CREATE INDEX IF NOT EXISTS idx_problems_status ON problems(status);
CREATE INDEX IF NOT EXISTS idx_problems_source_type ON problems(source_type);

CREATE TRIGGER update_problems_updated_at
    BEFORE UPDATE ON problems
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- 3. Create problem_evaluation_criteria table
CREATE TABLE IF NOT EXISTS problem_evaluation_criteria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR(100) NOT NULL,
    question TEXT NOT NULL,
    suggestion TEXT,
    max_score INTEGER NOT NULL,
    display_order INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_problem_eval_criteria_active_order ON problem_evaluation_criteria(active, display_order);

CREATE TRIGGER update_problem_evaluation_criteria_updated_at
    BEFORE UPDATE ON problem_evaluation_criteria
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- 4. Alter student_groups table to add selected_problem_id
ALTER TABLE student_groups ADD COLUMN IF NOT EXISTS selected_problem_id BIGINT;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_student_groups_selected_problem'
          AND conrelid = 'student_groups'::regclass
    ) THEN
        ALTER TABLE student_groups
            ADD CONSTRAINT fk_student_groups_selected_problem
            FOREIGN KEY (selected_problem_id) REFERENCES problems(id) ON DELETE SET NULL;
    END IF;
END;
$$;

CREATE INDEX IF NOT EXISTS idx_student_groups_selected_problem_id ON student_groups(selected_problem_id);
